= JPMS with Kotlin Sandbox

*Features*

* JVM 11
* Java Platform Module System (JPMS)
* Multiple Kotlin Moudles

== Usage

* Build complete project `./gradlew build`
* Build individual project `./gradlew :component:shared-kernel:build`

== Troubleshoot

=== Class has been compiled by a more recent version of the Java Environment

* Check that your gradle uses the right JVM version `./gradlew --version`
* In IntelliJ
** Check the gradle it uses: Settings->Build, Execution,...->Build Tools->Gradle->Gradle JVM
** Right click your project and open the Module Settings->Project->Project SDK

== Gradle

The link:https://gradle.org/[Gradle] build tool is an alternative to link:https://maven.apache.org/[Maven].
It's built system consists of two major building blocks

1. project
2. task

A Gradle build system is made up of one or more projects and each project contains one or more tasks.
A project represents an artifact that needs to be built.

Gradle has a simple link:https://docs.gradle.org/current/userguide/command_line_interface.html[command-line interface].

* View all projects `./gradlew projects`
* View the available tasks `./gradlew tasks`

=== Wrapper

Please make sure you have the newest Gradle (>= v6) version installed if you run the `gradle wrapper` task.

=== BuildSrc

BuildSrc is a project in the root of your build.
Everything written there will be shared by all your build scripts.
We can use buildSrc to write our own gradle tasks, plugins or extensions functions that will be available in all `build.gradle.kts`.
The gradle team also recommends placing dependency versions there.

BuildSrc Plugins can be applied the same way as regular plugins.
We can specify an id alias by placing a properties file in `buildSrc/src/main/resources/META-INF.gradle-plugins`.

=== Test

Specifying test and test options is relatively straightforward using gradle.
The link:https://docs.gradle.org/current/userguide/java_testing.html[JavaTesting Guide] and the official docs for the link:https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html[Test Api] provide a good starting point.
They also help when it comes to defining a more complicated test setup using multiple testsets.

In our case we wrote a custom buildSrc plugin to define multiple testsets that can share code between them.
We could have also used the link:https://github.com/unbroken-dome/gradle-testsets-plugin[Gradle TestSets plugin], an example code base can be found link:https://github.com/Richargh/testsets-plugin-krdl-kt-sandbox[here].

=== Gradle Kotlin Dsl

* You can find lots of official link:https://github.com/gradle/kotlin-dsl-samples/tree/master/samples[Gradle Kotlin Dsl Samples] online
* The official docs provide a link:https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/[Migration Guide] from Groovy to Kotlin
* There is also the link:https://docs.gradle.org/current/userguide/kotlin_dsl.html[Gradle Kotlin DSL User Guide] to consider.

=== Plugins

Plugins can modify your build quite a lot.
For example they can add tasks or new extensions to a project.
They are usually added in the `plugins {}` block of a `build.gradle.kts`.
The normal way is to supply an `id("...")`.

If you want an executable jar, you would usually add the application plugin `plugins { id("org.gradle.application") }`.
Gradle provides aliases for the common plugin they supply.
So `id("org.gradle.application")` becomes `\`application\``.
JetBrains provides a different alias for all the kotlin plugins and `id("org.jetbrains.kotlin.jvm")` becomes `kotlin("jvm")`.

The link:https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:multi_project_builds_applying_plugins[Gradle Kotlin Dsl convention] is to declare plugins and their version in the root project build script without applying them.
The subprojects can then apply the plugins on demand but should not specify the version.

=== Scripts

You can create a buildSrc plugin if your `build.gradle.kts` becomes to big.
Depending on your use case you can also split your `.kts` into multiple ones and reapply the script with `apply(from = "script-plugin.gradle.kts")`.
